### ISSUE TITLE
The URL for IMDA-FACE dataset

### ISSUE THREAD

**Issue by zhangxiaodu** [fwang91/IMDb-Face#1]
The URL you released is not obtained. Chould you please send me the URL? 
Thank you very much!

**Comment by fwang91** [comment]
We are preparing the materials and the files of url and meta-information will be released soon.

**Comment by zhangxiaodu** [comment]
@fwang91 Thank you very much. I'm looking forward to it.

**Comment by hustzeyu** [comment]
I am looking forward to download it too, and thank you! Good job Sensetime!

**Comment by BrettLL** [comment]
looking forward to it~ Good job!!

**Comment by bruinxiong** [comment]
Looking forward to download this dataset. Thanks!

**Comment by tianyunfei** [comment]
When will the dataset be released?

**Comment by fwang91** [comment]
Thank you for your attention to IMDb-Face. The URL file has been released.

**Comment by markitosha** [comment]
URLs are corrupted. Could you release IMDBIndex of images (like rm2189051904) as you did for the persons (nm1783794) before?
