### ISSUE TITLE
duplicate rows in IMDb-Face.csv

### ISSUE THREAD

**Issue by mingzhang96** [fwang91/IMDb-Face#5]
I found that there are some duplicate rows in `IMDb-Face.csv`. For example, for person named `Peter_Loung`, there are tens of rows recording the same information. You can search `nm0522014` in `IMDb-Face.csv` to prove it.

I try to delete the duplicate rows in `IMDb-Face.csv`, and the number of rows decreases from 1662888 to 1632928. Is there anything wrong with the csv file?

**Comment by fwang91** [comment]
Sorry, you can directly ignore it. We will update the csv file later.

**Comment by mingzhang96** [comment]
ok, thx.
